blinding_DLEQ = "1116886504764407895557380297807419853051642440851866282013869627207780256631"
challenge_bytes = [
    "50",
    "222",
    "47",
    "128",
    "126",
    "136",
    "164",
    "16",
    "39",
    "83",
    "37",
    "243",
    "94",
    "111",
    "218",
    "248",
    "122",
    "134",
    "40",
    "55",
    "20",
    "56",
    "126",
    "66",
    "241",
    "173",
    "3",
    "130",
    "153",
    "26",
    "69",
    "179",
]
response_div_BabyJubJub = [
    "33",
    "100",
    "205",
    "56",
    "5",
    "197",
    "67",
    "148",
    "132",
    "142",
    "187",
    "207",
    "137",
    "35",
    "254",
    "192",
    "19",
    "22",
    "124",
    "15",
    "67",
    "44",
    "131",
    "136",
    "109",
    "50",
    "218",
    "148",
    "248",
    "112",
    "202",
    "28",
]
response_div_ed25519 = [
    "12",
    "159",
    "248",
    "44",
    "187",
    "131",
    "135",
    "249",
    "195",
    "24",
    "88",
    "165",
    "179",
    "181",
    "208",
    "197",
    "219",
    "103",
    "200",
    "142",
    "249",
    "193",
    "92",
    "210",
    "247",
    "180",
    "167",
    "157",
    "130",
    "64",
    "108",
    "75",
]
response_BabyJubJub = [
    "2",
    "17",
    "25",
    "123",
    "115",
    "113",
    "3",
    "14",
    "83",
    "174",
    "58",
    "75",
    "217",
    "198",
    "151",
    "255",
    "77",
    "16",
    "223",
    "65",
    "110",
    "209",
    "5",
    "155",
    "255",
    "164",
    "245",
    "29",
    "4",
    "55",
    "232",
    "242",
]
response_ed25519 = [
    "4",
    "103",
    "94",
    "57",
    "147",
    "43",
    "141",
    "88",
    "72",
    "50",
    "147",
    "4",
    "102",
    "156",
    "92",
    "211",
    "2",
    "233",
    "134",
    "241",
    "129",
    "54",
    "225",
    "65",
    "55",
    "115",
    "97",
    "120",
    "167",
    "85",
    "66",
    "223",
]
witness_i = "1796148635072644198528993709965250712161260876517187943861025917858310665127"
witness_im1 = "1050880143194726245149331375778752380248764928599673665220329869083862418411"

[T_i]
x = "16679947990868408797902287064451793275229033762076024843492214207778368656132"
y = "16585011463647692774550235489627037517630060058826267327304811949465453350012"

[T_im1]
x = "4840908652896882468597986170489043372341517135369958638351822584547862717134"
y = "20615593023145717315617721146021267392717228018408609707365460960822748655249"
