blinding_DLEQ = "1824000560541823844334195987917808911758893445581231260324960136447110158619"
challenge_bytes = [
    "16",
    "58",
    "142",
    "218",
    "69",
    "137",
    "31",
    "255",
    "77",
    "243",
    "116",
    "31",
    "52",
    "76",
    "90",
    "27",
    "232",
    "12",
    "8",
    "13",
    "134",
    "158",
    "205",
    "4",
    "21",
    "235",
    "63",
    "196",
    "176",
    "239",
    "157",
    "212",
]
response_div_BabyJubJub = [
    "1",
    "218",
    "2",
    "18",
    "197",
    "1",
    "168",
    "110",
    "121",
    "126",
    "167",
    "82",
    "160",
    "198",
    "138",
    "55",
    "108",
    "220",
    "249",
    "153",
    "19",
    "15",
    "104",
    "47",
    "111",
    "240",
    "58",
    "208",
    "139",
    "35",
    "146",
    "91",
]
response_div_ed25519 = [
    "0",
    "179",
    "52",
    "59",
    "43",
    "57",
    "192",
    "164",
    "98",
    "142",
    "191",
    "87",
    "96",
    "110",
    "199",
    "124",
    "203",
    "169",
    "72",
    "33",
    "255",
    "144",
    "202",
    "115",
    "27",
    "14",
    "207",
    "153",
    "177",
    "6",
    "231",
    "49",
]
response_BabyJubJub = "1626021089687799042306323369927819791496043434985013789325939855641786758018"
response_ed25519 = [
    "8",
    "212",
    "152",
    "129",
    "103",
    "33",
    "149",
    "73",
    "25",
    "77",
    "151",
    "224",
    "84",
    "230",
    "177",
    "245",
    "44",
    "239",
    "25",
    "225",
    "109",
    "96",
    "150",
    "20",
    "87",
    "114",
    "177",
    "218",
    "242",
    "7",
    "145",
    "208",
]
witness_i = "312163301934117133947386825241349474274597080750902507784973543869201264394"
witness_im1 = "1305972787479922221416521335344663601709377355989357840703079536436166096610"

[T_i]
x="0x0c212a6e5f891b402653a4e4ba77ac0f41d7182855e41458c22ea5ef2e8d3399"
y="0x072b4aaa8d07a055101db0611b9a4c9d14a036b45260527c901dd0c815bd84b9"

[T_im1]
x="0x0f6fd70d697cf0699087a8c00b4e09a7cc7005b99b450ed57353579371884af6"
y="0x2563aa8c0fce715a728beebc8ea789aba39db3ca8a0324c6160d6dedad03a4e0"
