blinding = "677747657238420344629545892862113350287078346014746041349885223968406425960"
blinding_DLEQ = "2144235790361468935043772530645960482335425265409759788405189265308656936802"
challenge_bytes = [
    "244",
    "26",
    "141",
    "141",
    "26",
    "33",
    "174",
    "44",
    "172",
    "62",
    "93",
    "61",
    "20",
    "158",
    "129",
    "136",
    "138",
    "61",
    "77",
    "64",
    "160",
    "117",
    "160",
    "101",
    "241",
    "75",
    "208",
    "244",
    "192",
    "232",
    "130",
    "39",
]
enc_2 = "1106098635239940503699041671268806550084808076753030002447195492368677905788"
nonce_peer = "941362473562958445854872797494637933207453843173119022055401701738008284186"
r_2 = "1072106140184681314352975995361112083950550273446077810276345662155291208434"
response_div_BabyJubJub = [
    "229",
    "32",
    "143",
    "75",
    "113",
    "63",
    "229",
    "174",
    "161",
    "218",
    "119",
    "35",
    "132",
    "100",
    "56",
    "52",
    "177",
    "120",
    "57",
    "228",
    "89",
    "99",
    "0",
    "157",
    "20",
    "88",
    "96",
    "20",
    "119",
    "23",
    "44",
    "115",
]
response_div_ed25519 = [
    "86",
    "159",
    "195",
    "153",
    "184",
    "214",
    "25",
    "77",
    "147",
    "109",
    "184",
    "144",
    "248",
    "206",
    "0",
    "209",
    "43",
    "78",
    "99",
    "142",
    "229",
    "221",
    "113",
    "23",
    "169",
    "53",
    "142",
    "87",
    "243",
    "100",
    "94",
    "248",
]
response_BabyJubJub = "854235210834499667423973962419711656071325410723767426196126191188738516312"
response_ed25519 = [
    "2",
    "181",
    "34",
    "27",
    "16",
    "113",
    "96",
    "218",
    "91",
    "117",
    "140",
    "181",
    "65",
    "84",
    "200",
    "176",
    "122",
    "124",
    "116",
    "167",
    "254",
    "232",
    "76",
    "52",
    "121",
    "234",
    "57",
    "141",
    "58",
    "13",
    "188",
    "3",
]
witness_0 = "2568166237609188807669846780611238875106975738847244883423726835401425291323"

[T_0]
x="0x291b35800fd8393946e6dd8196fc0282b6fa9b251c350c3c6cb554fb6e105710"
y="0x1a5a7ad350d85509a5472630861e9c722a3cf254e2c9ab44f8fb378543f16d2d"

[fi_2]
x="0x2344f802b1745e6261a1aad7a0739f31e0f865ed7f5544675ce8c926708b43e9"
y="0x02872987ca20f74801ae722d68e96e57b7927f3e0bb90c5ed270f01ef2579165"

[pubkey_KES]
x="0x0179cf6b6ae3d6ebc2bb82b052b799b788d370632c49888dd56d8137f562173a"
y="0x17301fd22acecfb6158e8bb8b42475a5fe1084deac5f64198ae3b8301840b568"

[pubkey_peer]
x="0x129421788fa90b2fa0f0a2ef436429af004b3a3d1277d55b9f244c350f5a03b3"
y="0x29cca3105b7b5213c35ce4b4d845552f88ea1c0278a7a7deb6eb8e4bc73af64f"
