blinding = "471130878694821421767495043715124818646838082994228710482818435737841729505"
blinding_DLEQ = "2327342367328809292261747900133029506775890989144681646436545750520275280017"
challenge_bytes = [
    "33",
    "149",
    "79",
    "101",
    "248",
    "237",
    "6",
    "233",
    "121",
    "21",
    "145",
    "220",
    "45",
    "175",
    "222",
    "94",
    "169",
    "193",
    "127",
    "33",
    "101",
    "79",
    "155",
    "140",
    "134",
    "117",
    "0",
    "244",
    "230",
    "95",
    "123",
    "28",
]
enc_2 = "2133187932969488891482796866340818757863010495788090995842941113489332347755"
nonce_peer = "1355724180131608782176526699125257070376803874828916939069797074586015854551"
r_2 = "2531871506730316212625558288238068908629702920909155150386394322777517053518"
response_div_BabyJubJub = [
    "12",
    "230",
    "34",
    "165",
    "51",
    "42",
    "234",
    "164",
    "223",
    "157",
    "171",
    "197",
    "130",
    "47",
    "36",
    "36",
    "100",
    "240",
    "158",
    "177",
    "25",
    "155",
    "118",
    "196",
    "64",
    "202",
    "105",
    "23",
    "77",
    "121",
    "245",
    "169",
]
response_div_ed25519 = [
    "4",
    "224",
    "104",
    "176",
    "213",
    "5",
    "32",
    "248",
    "100",
    "166",
    "207",
    "32",
    "193",
    "55",
    "176",
    "154",
    "195",
    "193",
    "8",
    "232",
    "70",
    "181",
    "151",
    "250",
    "104",
    "205",
    "79",
    "97",
    "216",
    "93",
    "205",
    "25",
]
response_BabyJubJub = [
    "2",
    "147",
    "143",
    "91",
    "150",
    "226",
    "119",
    "8",
    "198",
    "197",
    "117",
    "233",
    "43",
    "141",
    "208",
    "71",
    "58",
    "78",
    "211",
    "212",
    "12",
    "221",
    "233",
    "182",
    "48",
    "101",
    "59",
    "9",
    "150",
    "13",
    "220",
    "10",
]
response_ed25519 = [
    "0",
    "135",
    "183",
    "116",
    "187",
    "216",
    "182",
    "113",
    "243",
    "96",
    "165",
    "58",
    "250",
    "53",
    "157",
    "119",
    "5",
    "97",
    "14",
    "116",
    "170",
    "82",
    "102",
    "57",
    "59",
    "69",
    "38",
    "50",
    "8",
    "78",
    "186",
    "254",
]
witness_0 = "1050880143194726245149331375778752380248764928599673665220329869083862418411"

[T_0]
x = "4840908652896882468597986170489043372341517135369958638351822584547862717134"
y = "20615593023145717315617721146021267392717228018408609707365460960822748655249"

[fi_2]
x = "17713711882885110063779022776117531608623918274042858526274642583470506939821"
y = "16144821643727872301032593847084338671156099173877225561152286092334188144370"

[pubkey_KES]
x = "5299619240641551281634865583518297030282874472190772894086521144482721001553"
y = "16950150798460657717958625567821834550301663161624707787222815936182638968203"
