blinding = "1528284576486287820423915985344403217057064703542480562654580149210975655166"
blinding_DLEQ = "751346531972686614686625517649870897173944609040315185595448719729237979034"
challenge_bytes = [
    "71",
    "110",
    "191",
    "10",
    "213",
    "248",
    "104",
    "70",
    "21",
    "234",
    "193",
    "77",
    "132",
    "34",
    "255",
    "183",
    "172",
    "221",
    "6",
    "56",
    "233",
    "144",
    "147",
    "139",
    "194",
    "231",
    "41",
    "105",
    "135",
    "136",
    "8",
    "22",
]
enc_2 = "870231636560817994621406780295707928827291517262978312011145386935414900178"
nonce_peer = "825325917153115934824460561324676269947083468613848956977308058715365690372"
r_2 = "2521501989308291378216337818468698235255951916671519123153009373612833879206"
response_div_BabyJubJub = [
    "34",
    "24",
    "179",
    "165",
    "248",
    "112",
    "74",
    "88",
    "225",
    "131",
    "166",
    "204",
    "119",
    "201",
    "13",
    "241",
    "36",
    "58",
    "247",
    "43",
    "156",
    "227",
    "129",
    "65",
    "31",
    "138",
    "100",
    "15",
    "209",
    "51",
    "21",
    "162",
]
response_div_ed25519 = [
    "12",
    "227",
    "251",
    "144",
    "62",
    "73",
    "250",
    "185",
    "157",
    "34",
    "81",
    "159",
    "126",
    "55",
    "189",
    "208",
    "180",
    "194",
    "134",
    "147",
    "48",
    "141",
    "11",
    "170",
    "200",
    "91",
    "135",
    "113",
    "93",
    "214",
    "54",
    "65",
]
response_BabyJubJub = "270995456276034967115767375956945363531082071696302163103697530025553391184"
response_ed25519 = [
    "7",
    "92",
    "84",
    "121",
    "208",
    "137",
    "162",
    "164",
    "67",
    "14",
    "129",
    "162",
    "108",
    "82",
    "42",
    "233",
    "250",
    "60",
    "228",
    "248",
    "177",
    "48",
    "3",
    "211",
    "109",
    "149",
    "81",
    "18",
    "4",
    "86",
    "10",
    "165",
]
witness_0 = "1305972787479922221416521335344663601709377355989357840703079536436166096610"

[T_0]
x="0x0f6fd70d697cf0699087a8c00b4e09a7cc7005b99b450ed57353579371884af6"
y="0x2563aa8c0fce715a728beebc8ea789aba39db3ca8a0324c6160d6dedad03a4e0"

[fi_2]
x="0x19443db80493179c877e2a8ac8ee1bf3ddd56282a607bf307df543f4235320eb"
y="0x2104f91fd6dcc0614e6c8c5095a978741796ed343f75fc1cbbe367b388a0bf31"

[pubkey_KES]
x="0x0b374fb48fa84ddc063eadc3ee16f9d4772299f9efd248a154672bdbe1796104"
y="0x0781ea603740816860044b6c4cceece92a02917e65fa930df61ec2cc5f7026a5"
